"""Per-product metrics facade (§15).

Phase 6 ships the interface as a safe no-op so the engine is fully wired;
Phase 7 backs it with the Prometheus exporter on port 8100+N. Keeping the
call sites identical to the kraken engine means the port stays line-for-line
comparable.
"""

from __future__ import annotations


class BotMetrics:
    def __init__(self, product: str):
        self.product = product

    def update_emas(self, fast: float, slow: float, mid: float) -> None: ...
    def update_pnl(self, realized: float, unrealized: float) -> None: ...
    def update_position(self, qty: float, sl: float, tp: float) -> None: ...
    def update_signal(self, signal: str, exhaustion_active: bool = False) -> None: ...
    def inc_orders_placed(self) -> None: ...
    def inc_orders_filled(self) -> None: ...
    def inc_sl_hit(self) -> None: ...
    def inc_tp_hit(self) -> None: ...
